import "./globals.css";
import Head from "next/head";

export const metadata = {
  title: "!JokesDev",
  description: "Generated by Kenneth Manuel",
  icons: {
    icon: "/logo.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="/logo.png" />
      </Head>
      <body>{children}</body>
    </html>
  );
}
